name: 'Vue to Github Pages'
branding:
  icon: 'activity'  
  color: 'blue'
description: 'This Action will Build your Vue Project and deploy it to Github Pages'
inputs:
  username:
    description: 'Your username'
    required: true
  reponame:
    description: 'Your reponame'
    required: true
  token:
    description: 'Your Github token'
    required: true
  useyarn:
    description: 'Use yarn to build'
    required: false
    default: false
runs:
  using: "composite"
  steps:
      - name: Build Vue
        run: entrypoint.sh
        shell: bash
        env:
          USERNAME: ${{ inputs.username }}
          REPONAME: ${{ inputs.reponame }}
          TOKEN: ${{ inputs.token }}
          USEYARN: ${{ inputs.useyarn }}
