name: 'Cross-deploy NextJS Website'
branding:
  icon: 'activity'  
  color: 'blue'
description: 'This action builds and deploys your NextJS Website to a repo of your choice w/ Github Pages enabled.'
inputs:
  username:
    description: 'Your Github Username'
    required: true
  reponame:
    description: 'Your reponame'
    required: true
  token:
    description: 'Your SSH PUBLIC Key'
    required: true
  useyarn:
    description: 'Use Yarn to build'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Make entrypoint.sh executable
      run: chmod +x ./entrypoint.sh
      shell: bash
    - name: Build and Deploy
      run: entrypoint.sh
      shell: bash
      env:
        USERNAME: ${{ inputs.username }}
        REPONAME: ${{ inputs.reponame }}
        TOKEN: ${{ inputs.token }}
        USEYARN: ${{ inputs.useyarn }}
