name: 'Cross-deploy NextJS Website'
branding:
  icon: 'activity'  
  color: 'blue'
description: 'This action builds and deploys your NextJS Website to a repo of your choice w/ Github Pages enabled.'
inputs:
  username:
    description: 'Your Github Username'
    required: true
  reponame:
    description: 'Your reponame'
    required: true
  token:
    description: 'Your SSH PUBLIC Key'
    required: true
  useyarn:
    description: 'Use Yarn to build'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Build and Deploy
      run: |
        echo "$TOKEN" > ~/.ssh/id_rsa.pub

        git config --global user.email "CI@DUMBSPACEDOG.DEPLOYNEXTJS.ACTION"
        git config --global user.name "Github Actions"

        # Build the project
        if [ -z "$USEYARN" ] then
            npm install
            npm run build
            npm run export
        else
            yarn install
            yarn build
            yarn export
        fi



        mv out /tmp/out
        cd /tmp/out

        # Push the build to the gh-pages branch
        git init
        git add .
        git commit -m "Deploy to Github Pages via Deploy Action"
        git push --force --quiet "ssh://$USERNAME@github.com/$REPONAME.git" master:gh-pages
      shell: bash
      env:
        USERNAME: ${{ inputs.username }}
        REPONAME: ${{ inputs.reponame }}
        TOKEN: ${{ inputs.token }}
        USEYARN: ${{ inputs.useyarn }}
